### ISSUE TITLE
broken with newest chromium?

### ISSUE THREAD

**Issue by yardenac** [Lyrrad/NewsBlurBackgroundTab#11]
After upgrading to Chromium 68, this extension is no longer working.

**Comment by Lyrrad** [comment]
Hmm... it still seems to work for me in Chrome 68. Does it work in a new profile without any other extensions?

**Comment by yardenac** [comment]
Okay, after more testing, it's not completely broken. When I open a story in newsblur and press "o" to open it in a new tab, the tab does open in the background. However, if I press "x" to collapse the story and then "o", the new tab grabs focus. IIRC this didn't use to happen. Can you confirm? Thanks.

And yes, I'm testing this with a clean slate chromium.

**Comment by Lyrrad** [comment]
Closing since it still seems to work for me in 2021. Reopen if it's still happening.
