### ISSUE TITLE
Does not work with international keyboard layout

### ISSUE THREAD

**Issue by zsoltika** [Lyrrad/NewsBlurBackgroundTab#7]
Test case: try the extension with US keyboard layout. --> tab opens in background. Switch to hungarian layout, hit ; on the same newsblur tab as before --> nothing happens.

**Comment by Lyrrad** [comment]
Hi,  I've added an option to customize the hotkey.  This should allow you to use any (ASCII) key you want on any keyboard.  I'll test it out for a bit before pushing it to the Web store (probably this weekend).  You can try it out by downloading from the develop branch and loading the unpacked extension.

**Comment by zsoltika** [comment]
Hi,
thanks for your work, I did try it with 'w' and it works as expected. But if I set it to 'o' or 'v' (which are official shortchuts for Newsblur) - because of muscle memory - that opens two tabs of the same article (and the second in foreground). 
Anyhow I can live with 'w'. :+1: 
Thanks again,
Zsolt

**Comment by Lyrrad** [comment]
I haven't been able to figure out how to disable existing Newsblur keyboard shortcuts with an extension yet. Hopefully they come out with customizable shortcuts or let us disable some existing ones soon.
